# DEBIAN_TAG is the tag of the docker image used for the build jobs. If the
# image doesn't exist yet, the docker-image stage generates it.
#
# In order to generate a new image, one should generally change the tag.
# While removing the image from the registry would also work, that's not
# recommended except for ephemeral images during development: Replacing an
# image after a significant amount of time might pull in newer versions of
# gcc/clang or other packages, which might break the build with older commits
# using the same tag.
#
# After merging a change resulting in generating a new image to the main
# repository, it's recommended to remove the image from the source repository's
# container registry, so that the image from the main repository's registry
# will be used there as well.  You can manage your images on your fork of:
# https://gitlab.freedesktop.org/xorg/xserver/container_registry
variables:
    UPSTREAM_REPO: xorg/xserver
    DEBIAN_VERSION: testing-slim
    DEBIAN_EXEC: 'bash .gitlab-ci/debian-install.sh'

    DEBIAN_TAG: "2019-09-03"
    IMAGE_LOCAL: "$CI_REGISTRY_IMAGE/debian/$DEBIAN_VERSION:$DEBIAN_TAG"

include:
  - project: 'wayland/ci-templates'
    ref: c73dae8b84697ef18e2dbbf4fed7386d9652b0cd
    file: '/templates/debian.yml'

stages:
    - docker-image
    - build-and-test

# Retry jobs after runner system failures
.retry: &retry
  retry:
    max: 2
    when:
      - runner_system_failure

debian-testing:
  extends: .debian@container-ifnot-exists
  stage: docker-image
  <<: *retry

.common-build-and-test:
    <<: *retry
    stage: build-and-test
    image: $IMAGE_LOCAL
    artifacts:
        when: on_failure
        paths:
            - build/test/piglit-results/
    cache:
        paths:
            - ccache/
    variables:
        LC_ALL: C.UTF-8
    before_script:
        - export CCACHE_BASEDIR="$PWD"
        - export CCACHE_DIR="$PWD/ccache"
        - export CCACHE_COMPILERCHECK=content
        - export PATH="/usr/lib/ccache:$PATH"
        - ccache --zero-stats
        - ccache --show-stats
    after_script:
        - CCACHE_DIR="$PWD/ccache" ccache --show-stats

autotools-build-and-test:
    extends: .common-build-and-test
    script:
        - mkdir build/
        - cd build/
        - ../autogen.sh --prefix=/usr
        - make -j$(nproc) distcheck
        - PIGLIT_DIR=/root/piglit XTEST_DIR=/root/xts make -j$(nproc) check

meson-build-and-test:
    extends: .common-build-and-test
    variables:
        PIGLIT_DIR: /root/piglit
        XTEST_DIR: /root/xts
    script:
        - meson -Dprefix=/usr -Dxephyr=true build/
        - ninja -C build/ install
        - ninja -C build/ test
