variables:
   DEBIAN_X86_BUILD_BASE_IMAGE: "debian/x86_build-base"
   DEBIAN_BASE_TAG: "2022-09-12-virglrenderer"

   DEBIAN_X86_BUILD_IMAGE_PATH: "debian/x86_build"
   DEBIAN_BUILD_TAG: "2022-09-14-add-jq"

   DEBIAN_X86_BUILD_MINGW_IMAGE_PATH: "debian/x86_build-mingw"
   DEBIAN_BUILD_MINGW_TAG: "2022-08-25-shellcheck"

   DEBIAN_X86_TEST_BASE_IMAGE: "debian/x86_test-base"

   DEBIAN_X86_TEST_IMAGE_PATH: "debian/x86_test-gl"
   DEBIAN_X86_TEST_GL_TAG: "2022-09-14-add-jq"
   DEBIAN_X86_TEST_VK_TAG: "2022-09-14-add-jq"

   FEDORA_X86_BUILD_TAG: "2022-08-25-shellcheck"
   KERNEL_ROOTFS_TAG: "2022-09-14-add-jq"

   WINDOWS_X64_VS_PATH: "windows/x64_vs"
   WINDOWS_X64_VS_TAG: "2022-08-17-bump"

   WINDOWS_X64_BUILD_PATH: "windows/x64_build"
   WINDOWS_X64_BUILD_TAG: "2022-08-17-bump"

   WINDOWS_X64_TEST_PATH: "windows/x64_test"
   WINDOWS_X64_TEST_TAG: "2022-08-17-bump"
