# Keep the tags below under 20 chars each, as they end up combined into
# docker image tags, and docker has a length limit of 128 chars total in tags.
#
# The word after the date doesn't need to be overly descriptive, it exists
# purely to avoid the risk of two people updating an image tag on the same day
# while working on different changes, so it doesn't matter whether that word
# will make sense to someone else. Aim for "nobody else will pick that word
# for their change".
#
# If you update a tag and you get an error like this:
#     cannot parse input: "$image:$tag": invalid reference format
# check the length of $tag; if it's > 128 chars you need to shorten your tag.

variables:
   DEBIAN_X86_64_BUILD_BASE_IMAGE: "debian/x86_64_build-base"
   DEBIAN_BASE_TAG: "20241011-deqpr"

   DEBIAN_X86_64_BUILD_IMAGE_PATH: "debian/x86_64_build"
   DEBIAN_BUILD_TAG: "20240910-SDK614"

   DEBIAN_X86_64_TEST_BASE_IMAGE: "debian/x86_64_test-base"
   DEBIAN_ARM64_TEST_BASE_IMAGE: "debian/arm64_test-base"

   DEBIAN_X86_64_TEST_IMAGE_GL_PATH: "debian/x86_64_test-gl"
   DEBIAN_ARM64_TEST_IMAGE_GL_PATH: "debian/arm64_test-gl"
   DEBIAN_X86_64_TEST_IMAGE_VK_PATH: "debian/x86_64_test-vk"
   DEBIAN_ARM64_TEST_IMAGE_VK_PATH: "debian/arm64_test-vk"
   DEBIAN_X86_64_TEST_ANDROID_IMAGE_PATH: "debian/x86_64_test-android"

   DEBIAN_TEST_ANDROID_TAG: "20241016-zz-top"
   DEBIAN_TEST_GL_TAG: "20241017-piglit-79"
   DEBIAN_TEST_VK_TAG: "20241017-piglit-79"
   KERNEL_ROOTFS_TAG: "20241018-oblique"

   DEBIAN_PYUTILS_IMAGE: "debian/x86_64_pyutils"
   DEBIAN_PYUTILS_TAG: "20241002-pyutils"

   ALPINE_X86_64_BUILD_TAG: "20240814-var"
   ALPINE_X86_64_LAVA_SSH_TAG: "20240401-wlproto"
   FEDORA_X86_64_BUILD_TAG: "20240717-pyyaml"
   KERNEL_TAG: "v6.6.21-mesa-f8ea"
   KERNEL_REPO: "gfx-ci/linux"
   PKG_REPO_REV: "bca9635d"

   WINDOWS_X64_MSVC_PATH: "windows/x86_64_msvc"
   WINDOWS_X64_MSVC_TAG: "20240827-v143"

   WINDOWS_X64_BUILD_PATH: "windows/x86_64_build"
   WINDOWS_X64_BUILD_TAG: "20240910-SDK614"

   WINDOWS_X64_TEST_PATH: "windows/x86_64_test"
   WINDOWS_X64_TEST_TAG: "20240910-SDK614"
