[[piglit]]
piglit_folder = "/piglit"
profile = "gpu"
process_isolation = true
timeout = 180.0
skips = ["install/freedreno-a6xx-skips.txt", "install/freedreno-a618-skips.txt"]
  [piglit.env]
  PIGLIT_NO_WINDOW = "1"
