# Basic test set
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
fraction = 13
renderer_check = "Turnip Adreno .* 630"

# force-gmem testing
# Autotuner forces sysmem on most CTS tests
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
prefix = "gmem-"
fraction = 30
[deqp.env]
TU_DEBUG = "gmem,forcebin"

# force-sysmem testing
[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
include = ["dEQP-VK.renderpass.*"]
prefix = "bypass-"
fraction = 30
[deqp.env]
TU_DEBUG = "sysmem"

[[deqp]]
deqp = "/deqp/external/vulkancts/modules/vulkan/deqp-vk"
caselists = ["/deqp/mustpass/vk-master.txt"]
skips = ["install/freedreno-a630-premerge-skips.txt"]
include = ["dEQP-VK.graphicsfuzz.*"]
prefix = "spill-"
[deqp.env]
IR3_SHADER_DEBUG = "spillall"
