# x11
[[deqp]]
deqp = "/deqp-gles/modules/egl/deqp-egl-x11"
caselists = ["/deqp-gles/mustpass/egl-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]

[[deqp]]
deqp = "/deqp-gles/modules/egl/deqp-egl-wayland"
caselists = ["/deqp-gles/mustpass/egl-main.txt"]
skips = ["install/freedreno-a6xx-skips.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]
prefix = "wayland-"
