[[deqp]]
deqp = "/deqp-gles/modules/gles2/deqp-gles2"
caselists = ["/deqp-gles/mustpass/gles2-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0
version_check = "GL ES 3.2.*git"
renderer_check = "zink.*llvmpipe"

[[deqp]]
deqp = "/deqp-gles/modules/gles3/deqp-gles3"
caselists = ["/deqp-gles/mustpass/gles3-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0

[[deqp]]
deqp = "/deqp-gles/modules/gles31/deqp-gles31"
caselists = ["/deqp-gles/mustpass/gles31-main.txt"]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0

[[deqp]]
deqp = "/deqp-gl/external/openglcts/modules/glcts"
caselists = [
    "/deqp-gl/mustpass/gl46-main.txt",
    "/deqp-gl/mustpass/gl46-khr-single.txt",
]
deqp_args = [
    "--deqp-surface-width=256",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-visibility=hidden"
]
timeout = 180.0

[[piglit]]
piglit_folder = "/piglit"
profile = "gpu"
process_isolation = true
timeout = 180.0
  [piglit.env]
  # Disable validation on piglit.  We end up with use-after-frees from
  # piglit_report() -> exit() having freed validation layer state, with a
  # st_glFlush() -> tc_batch_execute() -> zink_set_vertex_buffers ->
  # vulkan_layer_chassis::CmdPipelineBarrier2() (etc.) happening after that
  # somehow.
  ZINK_DEBUG = ""
