[[deqp]]
deqp = "/deqp/modules/gles31/deqp-gles31"
caselists = ["/deqp/mustpass/gles31-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]
version_check = "GL ES 3.1.*git"
renderer_check = "V3D 4.2.14"
prefix = "asan-"

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [
    "/deqp/mustpass/gles31-khr-main.txt",
]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]
prefix = "asan-"

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = ["/deqp/mustpass/gl31-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]
prefix = "asan-"
