[[deqp]]
deqp = "/deqp/modules/gles31/deqp-gles31"
caselists = ["/deqp/mustpass/gles31-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]
version_check = "GL ES 3.1.*git"
renderer_check = "V3D"

[[deqp]]
deqp = "/deqp/modules/gles3/deqp-gles3"
caselists = ["/deqp/mustpass/gles3-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]

[[deqp]]
deqp = "/deqp/modules/gles2/deqp-gles2"
caselists = ["/deqp/mustpass/gles2-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = [
    "/deqp/mustpass/gles31-khr-main.txt",
    "/deqp/mustpass/gles3-khr-main.txt",
    "/deqp/mustpass/gles2-khr-main.txt",
]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]

[[deqp]]
deqp = "/deqp/external/openglcts/modules/glcts"
caselists = ["/deqp/mustpass/gl31-main.txt"]
deqp_args = [
    "--deqp-gl-config-name=rgba8888d24s8ms0",
    "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer",
    "--deqp-surface-width=256",
    "--deqp-visibility=hidden",
]

[[piglit]]
piglit_folder = "/piglit"
profile = "gpu"
process_isolation = true
  [piglit.env]
  PIGLIT_PLATFORM = "mixed_glx_egl"

# wayland
[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-wayland"
caselists = ["/deqp/mustpass/egl-main.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]
prefix = "wayland-"

# x11
[[deqp]]
deqp = "/deqp/modules/egl/deqp-egl-x11"
caselists = ["/deqp/mustpass/egl-main.txt"]
deqp_args = [
    "--deqp-surface-width=256", "--deqp-surface-height=256",
    "--deqp-surface-type=pbuffer", "--deqp-visibility=hidden",
    "--deqp-gl-config-name=rgba8888d24s8ms0",
]
prefix = "x11-"
